# Generated by Django 5.1.6 on 2025-03-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0002_rename_healthgoals_daily_goals'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daily_goals',
            table='levelUp.HealthGoals',
        ),
    ]
