# Generated by Django 5.1.6 on 2025-03-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0003_alter_daily_goals_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_goals',
            name='user_id',
        ),
    ]
