# Generated by Django 5.1.6 on 2025-03-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0004_remove_daily_goals_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daily_goals',
            table='levelup.HealthGoals',
        ),
    ]
