# Generated by Django 5.1.6 on 2025-03-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0007_alter_daily_goals_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_goals',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='daily_goals',
            old_name='daily_calories',
            new_name='daily_calorie_goal',
        ),
        migrations.RenameField(
            model_name='daily_goals',
            old_name='daily_steps',
            new_name='daily_steps_goal',
        ),
        migrations.RenameField(
            model_name='daily_goals',
            old_name='id',
            new_name='goal_id',
        ),
    ]
