# Generated by Django 5.1.6 on 2025-03-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0009_daily_goals_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_goals',
            old_name='user_id',
            new_name='user',
        ),
    ]
