# Generated by Django 5.1.6 on 2025-03-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0010_rename_user_id_daily_goals_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_goals',
            name='created_at',
        ),
    ]
