# Generated by Django 5.1.6 on 2025-03-08 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0011_remove_daily_goals_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_goals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
