# Generated by Django 5.1.6 on 2025-03-29 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedDatabase',
            fields=[
                ('Food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Food', models.CharField(max_length=255)),
                ('Measure', models.CharField(max_length=100)),
                ('Grams', models.IntegerField()),
                ('Calories', models.IntegerField(blank=True, null=True)),
                ('Proteins', models.IntegerField(blank=True, null=True)),
                ('Fats', models.IntegerField(blank=True, null=True)),
                ('Carbs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fooddata',
            },
        ),
        migrations.CreateModel(
            name='LoggedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loggedmeal',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='meals.loggedmeal')),
            ],
        ),
    ]
