# Generated by Django 5.1.7 on 2025-03-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('FoodID', models.IntegerField(primary_key=True, serialize=False)),
                ('FoodCode', models.IntegerField()),
                ('FoodGroupID', models.IntegerField()),
                ('FoodSourceID', models.IntegerField()),
                ('FoodDescription', models.TextField()),
                ('FoodDateOfEntry', models.DateField()),
                ('ScientificName', models.CharField(max_length=255)),
            ],
        ),
    ]
