# Generated by Django 5.1.7 on 2025-03-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_fooddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedMeal',
            fields=[
                ('foodid', models.IntegerField(primary_key=True, serialize=False)),
                ('fooddescription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fooddata',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FoodData',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='created_at',
            new_name='logged_at',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.AddField(
            model_name='meal',
            name='predefined_meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='logged_meals', to='meals.predefinedmeal'),
            preserve_default=False,
        ),
    ]
