# Generated by Django 5.1.7 on 2025-03-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedMeal',
            fields=[
                ('meal_id', models.AutoField(db_column='meal_id', primary_key=True, serialize=False)),
                ('meal_name', models.CharField(db_column='meal_name', max_length=255)),
                ('calories', models.IntegerField(db_column='calories')),
                ('protein', models.IntegerField(db_column='protein')),
                ('carbs', models.IntegerField(db_column='carbs')),
                ('fats', models.IntegerField(db_column='fats')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'meals',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
