# Generated by Django 5.1.7 on 2025-03-21 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_preferences'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height_m', models.FloatField()),
                ('mass_kg', models.FloatField()),
                ('age_yr', models.FloatField()),
                ('sex', models.CharField(max_length=16)),
            ],
        ),
    ]
