# Generated by Django 5.1.7 on 2025-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_healthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='age_yr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='height_m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='mass_kg',
            field=models.FloatField(null=True),
        ),
    ]
